language: node_js
node_js:
  - '7'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache: yarn
before_script:
  - npm start
script:
  - npm test
after_script:
  - 'cat coverage/report-lcov/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
